# -*- encoding : utf-8 -*-
<% module_namespacing do -%>
class <%= class_name %> < <%= parent_class_name.classify %>
  # extends ...................................................................
  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
<% if attributes.any?(&:password_digest?) -%>
   has_secure_password
<% end -%>

 # relationships .............................................................
 <% attributes.select(&:reference?).each do |attribute| -%>
   belongs_to :<%= attribute.name %><%= ', polymorphic: true' if attribute.polymorphic? %>
 <% end -%>

   # validations ...............................................................
   # callbacks .................................................................
   # scopes ....................................................................
   # additional config .........................................................
   # class methods .............................................................
   # public instance methods ...................................................
   # protected instance methods ................................................
   # private instance methods ..................................................

end
<% end -%>
