# -*- encoding : utf-8 -*-
# == Schema Information
#
# Table name: settings
#
#  id         :integer          not null, primary key
#  var        :string(255)      not null
#  value      :text
#  thing_id   :integer
#  thing_type :string(30)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class SiteSettings < RailsSettings::CachedSettings
  # extends ...................................................................
  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
	attr_accessible :var, :value

  # relationships .............................................................
  # validations ...............................................................
  validates :var, :presence => true
  validates :value, :presence => true

  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
